# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Javier Rodriguez Puigvert
title: Phd Candidate
title: University Zaragoza, group "Robótica, Percepción y Tiempo Real (RoPeRT)"
email: jrp@unizar.es
# email_title: Email (Email title override)
phone: (+34)638450611
# phone_title: Phone (Phone title override)
website: CV
website_link: ./images/cv.pdf

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: JRPuigvert
linkedin_username: javier-rodriguez-puigvert-b4642a66
github_username: jrodriguezpuigvert

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: ./images/profile.jpg
about_content:
   I am researching Bayesian Deep Learning, Computer Vision, and SLAM and am advised by [Javier Civera](https://www.linkedin.com/in/jcivera/) and [Ruben Martinez-Cantin](http://webdiis.unizar.es/~rmcantin/) under my PhD programme which I started in 2020. My trajectory has been driven by my interest in robotics, artificial intelligence, and augmented reality. At my last work station Cologne Intelligence GmbH, Germany, I brought forward the company's research into visual SLAM systems combined with augmented reality platforms for mobile devices. I completed by Master Thesis on visual localisation systems at TH Köln, Germany. I enriched my university studies by participating with the ["Eurobotics Engineering"](https://arc-robots.org/) team in international autonomous robotics competitions. 
content:
  - title: My Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout:
        title: Bayesian Deep Networks for Supervised Single-View Depth Learning
        link: Link to project (https://arxiv.org/abs/2104.14202)
        link_text: Link Text
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
        youtube-id: nj5_eVFQVZ8
        autors: "Javier Rodríguez-Puigvert, Rubén Martínez-Cantín, Javier Civera"
        source: "ArXiv, 29 Apr 2021"
        abstract: "Uncertainty quantification is a key aspect in robotic perception, as overconfident or point estimators can lead to collisions and damages to the environment and the robot. In this paper, we evaluate scalable approaches to uncertainty quantification in single-view supervised depth learning, specifically MC dropout and deep ensembles."
      - layout:
        title: Localization Service Using Sparse Visual Information Based on Recent Augmented Reality Platforms
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
        youtube-id: UPYLnRE75t4	
        autors: "Javier RodríguezPuigvert; Till Krempel; Arnulph Fuhrmann"
        source: "ISMAR (In Adjunct Proceedings of the IEEE International Symposium for Mixed and Augmented Reality 2018) Munich, 16 Oct 2018"
        abstract: "We propose a localization service based on sparse visual information using ARCore, a state-of-the-art augmented reality platform for mobile devices. Our service is constituted by two components - front-end and back-end. On the front-end, using the point cloud generated by ARCore as feature points, a corresponding binary keypoint descriptor algorithm like ORB or FREAK is computed to describe the place. On the back-end, this binary descriptor is searched in a map using the bags of binary words technique, responding with the position of the recognized place."

      - layout: 
        title: "Obstacle Collision Avoidance System for visually impaired based on Tango"
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
        youtube-id: UPYLnRE75t4	
        autors: "Javier Rodríguez Puigvert"
        source: "Technische Hochschule Köln, 24 Apr 2017"
        abstract: "In order to move freely around the space, a user could use this system as a virtual white cane. The Obstacle Collision Avoidance System intends to assist visually impaired people during the obstacle avoidance process using the depth perception of a Tango enable device. "

  - title: Talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: 
        title: Tango Step by Step. Indoor Positioning and Navigation
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
        youtube-id: 4R-Sc8LHzfM
        autors: "Digility Conference and Expo 2017. Cologne,Germany."

      - layout: 
        title: Indoor Navigation with Google Tango
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
        youtube-id: 5jfydcCPt4s
        autors: "Droidcon UK 2016. London, United Kingdom"

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
